# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='prov',
            field=models.ManyToManyField(blank=True, related_name='serv', to='proveedores.Proveedor'),
        ),
    ]
