# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fplaneado', models.DateTimeField()),
                ('fcompletado', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('tar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea.Tarea')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
