# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subtarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtarea',
            name='tar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tarea', to='tarea.Tarea'),
        ),
    ]
