# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.URLField(blank=True)),
                ('num_inv', models.IntegerField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=300)),
                ('croquis', models.ImageField(blank=True, upload_to=eventos.models.user_directory_path)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
