# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_tar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='tar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coment', to='tarea.Tarea'),
        ),
    ]
