# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='eventos.Evento'),
        ),
    ]
