# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fplaneado', models.DateTimeField()),
                ('fcompletado', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('prov', models.ManyToManyField(blank=True, to='proveedores.Proveedor')),
            ],
            options={
                'ordering': ('fplaneado',),
            },
        ),
    ]
