# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='subtar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='subtarea.SubTarea'),
        ),
    ]
